//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotocycleSales
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuongTrinhKM
    {
        public string MaChuongTrinh { get; set; }
        public string MaQuanLy { get; set; }
        public string MaLoaiKhach { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayHH { get; set; }
        public string DanhSachQuaTang { get; set; }
        public Nullable<double> VoucherGiamGia { get; set; }
    
        public virtual LoaiKhachHang LoaiKhachHang { get; set; }
        public virtual QuanLy QuanLy { get; set; }
    }
}
