//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotocycleSales
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiemKe
    {
        public string MaXe { get; set; }
        public Nullable<int> SoLuongCon { get; set; }
        public Nullable<int> SoLuongDaBan { get; set; }
        public string TinhTrang { get; set; }
        public System.DateTime NgayKiemKe { get; set; }
        public string MauSac { get; set; }
        public string MaCuaHang { get; set; }
    
        public virtual CuaHang CuaHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
